import Head from "next/head";
import { Toaster } from "react-hot-toast";
import { GlobalStyle } from "../styles/Global";

function HeadComponent() {
    return (
        <>
            <Head>
                <title>PokeStack</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div><Toaster /></div>
            <GlobalStyle />
        </>
    );
}



export default HeadComponent;