import Head from "next/head";

function HeadComponent() {
    return (
        <Head>
            <title>PokeStack</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}

export default HeadComponent;